version: "3"
services:
  app:
    container_name: vidly_container
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo_vidly_comp
    image: mongo
    ports:
      - "27017:27017"
